# Generated by Django 2.0.7 on 2018-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='slug',
            field=models.CharField(default='xxxxx', max_length=30),
        ),
    ]
