# Generated by Django 2.0.7 on 2018-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
