# Generated by Django 2.0.7 on 2018-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180903_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
