# Generated by Django 2.0.7 on 2018-09-12 16:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180912_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
    ]
